### PR TITLE
Feature/cpp msgpack sub

### PR DESCRIPTION
**Pull request by kyunwang**
I've made a small CPP sample file to demonstrate the subscription model of MQTT with MSGPack.
Have not gotten it to work yet with Publishing MSGPack data over MQTT.

Used a JSON library (interestingly enough) which makes the usage of the received data much more convenient and less complicated. Now allowing for unknown data structures to be consumed without any visitor pattern.

Also removed a submodule (mosquito) which was unused but sending errors during cmake builds.

More on the reasoning here: https://github.com/kyunwang/MQTT-MSGPack-CPP-Sample

### CODE REVIEW

**Comment by ralphkok** [comment]
Hi @kyunwang, just wanted to check that if converting to msgpack with the JSON library doesn't work (well), why we wouldn't use the msgpack library itself, as in the existing CPP example (see below)?
Looks straightforward enough to me.

```
std::stringstream buffer;
msgpack::pack(buffer, d);
tok = top.publish(buffer.str());
```

Cheers

**Comment by anselanza** [comment]
It seems that this JSON library _does_ support MessagePack, though.

See https://github.com/nlohmann/json#binary-formats-bson-cbor-messagepack-ubjson-and-bjdata

**Comment by anselanza** [comment]
Has this been resolved yet, @ralphkok or @kyunwang ?

**Comment by kyunwang** [comment]
Just saw this now 😄 didn't get any notifications
@ralphkok this JSON library does support msgpack, encoding and decoding to be specific. 

To me this was much more "familiar" and straight forward to implement as this subverts some cpp oddities from web dev me. Also, this avoid you needing to compile and download the whole msgpack library which is a big 👍🏻 to me. The JSON lib already handles it.

**Pull request merged**
