### PR TITLE
Feature/update js

### PR DESCRIPTION
**Pull request by anselanza**
At long last, this update gets round to improving the Javascript API - the JS Base Agent. It is a breaking change - not backwards-compatible - so it moves the JS Base Agent to v3.

TLDR; check out the `./examples/js/index.js` to see the new API in action. The differences are easy to spot if you're used to the old way.

# Major Changes

## Plugs are not stored 
We used to use methods on the TetherAgent class (`.createInput` and .`createOutput`) which not only created the Plug definition but also did **two** things:

- Added the new Plug to a private (internal) array of `inputs[]` and `outputs[]`
- Returned the Plug 

This potentially created some confusion: who "owns" the Plug? Is it the Tether Agent instance, or a variable stored by the end-user developer somewhere? Both?

In v3, plugs are created by calling 
- `new OutputPlug(...)` for Output Plugs - this is synchronous
- `await InputPlug.create(...)` for Input Plugs - this is **async** because it forces the end-user to wait for subscription to happen before using the Plug!

> For some reason, it is still possible to call `new InputPlug` and `new TetherAgent` even though these are both defined explicitly as `private constructor`, yet no error is thrown. JS isn't supposed to have private constructors, but TS definitely does. Seems to work in a TypeScript environment as expected (see below), but JS allows such silliness.

Screenshot 2023-11-03 at 17 01 56

Notice also that these are called `InputPlug` and `OutputPlug` now instead of the old `Input` and `Output` - this avoids some potential naming clashes and seems clearer.

The `agent` instance is passed in with the constructor in order to:
- build sensible default topics based on the Agent Role and ID as necessary
- allow messages to be published via `.publish(...)` in the case of OutputPlug
- allow standard Events to be emitted via `.on("message", ...)` when matching incoming messages in the case of InputPlug

One implication of this which might not be obvious at first: messages will be checked by each InputPlug rather than only "once" inside the TetherAgent instance. The InputPlug instances keep a reference to the agent (not the other way around, as previously), so they do `this.agent.getClient().on("message" ...`. This might be slightly more inefficient, since all incoming messages propagate Events regardless of which InputPlug they "belong" to, but only the topic is parsed at this stage (not the MessagePack contents, for example) so it's probably a minimal impact.

Each OutputPlug instance also retains a reference to the TetherAgent instance, which it uses for publishing.

In summary: the end-user developer needs to look after instances of InputPlug and OutputPlug themselves, and cannot call `.getInput` or `.getOutput` since the Plugs are not saved somewhere "else". This hopefully makes things clearer, and ensures that the developer focusses on the Plug level without having to also consider a somewhat abstract relation between Plugs and the TetherAgent.

### For TetherAgent
For `TetherAgent.create` the only required parameter is the `role`, which you always need to provide. The other parameter is `options?: TetherOptions` - it is both an optional parameter **and** the fields in the object are all optional! This makes it easy to pass in only the override options you need, e.g. `TetherAgent.create("mySpecialAgent", { id: "specificGroup" }` will only override the agent `ID`.

Even more useful is that what used to be called `overrides` (MQTT `IClientOptions`) is now labelled specifically `brokerOptions`, and we provide two default objects that are suitable for NodeJS/TCP and Browser/WebSocket connections respectively. By default, we use the NodeJS/TCP settings, but for web applications you set things up very easily with something like this:
```
import { TetherAgent, BROKER_DEFAULTS } from "tether-agent";
const agent = await TetherAgent.create("browserApplication", {
  brokerOptions: BROKER_DEFAULTS.browser,
});
```
... No need to remember to change protocol, port number, path, etc.

Another convenience: for both `BROKER_DEFAULTS.nodeJS` and `BROKER_DEFAULTS.browser` we connect to the MQTT Broker at `localhost` with the standard username+password for Tether as per our standard Docker setup and all other utilities developed so far. Of course, you can override any of this, but there is less to remember!

### Catching the weird "host" vs "hostname" quirk
The JS MQTT library has always behaved strangely when you change the `host` property but not the `hostname` property at the same time. The result is that `host` is effectively ignored, and you find yourself being connected to the wrong host name or IP address!

Yes, we could tell all users to always set both "host" and "hostname" together. But why not just auto-detect this situation and fix it for them? v3 does this: if the user specifies a "host" but forgets "hostname", we just set "hostname" to the same thing as the user specified for "host". Problem solved.

### For Plugs
`OutputPlug` now has a constructor with arguments as follows:
```
 agent: TetherAgent,
    name: string,
    options?: {
      overrideTopic?: string;
      publishOptions?: IClientPublishOptions;
    }
```
Notice that only the "name" is required. 

A key difference from the earlier version: `IClientPublishOptions` are provided at **instantiation** rather than on `.publish`. Defaults are used if nothing is provided. In other words, this config is **saved** and used for every `.publish` call, which seems more sensible.

Similarly, `InputPlug` now has a factory method `async create` with the following arguments
```
 agent: TetherAgent,
    name: string,
    options?: {
      overrideTopic?: string;
      subscribeOptions?: IClientSubscribeOptions;
    }
```
Again, only the "name" is required. The options for subscription get saved, same as for OutputPlug (this used to be inconsistent - Input(Plug) would save these options but Output(Plug) would not).

**Very important: there is no public or implicit `.subscribe` method any more.** Creating an Input Plug is assumed to be synonymous with subscribing. Previously, the end-user could either call `.subscribe` themselves or - confusingly - do an implicit `.subscribe` when calling `.onMessage` or `onMessageOnce`! This seemed like a very niche case to provide for, and just made things potentially confusing at times.

## Automatic (or manual) Connecting is simplified
Previously, we had a private method `.connect(overrides?: IClientOptions)` on `TetherAgent`. Confusingly, you could override some things related to the MQTT connection at this point rather than on `TetherAgent.create` in the first place... 

Instead, `.connect()` now takes no parameters, because it simply uses whatever has been set up in the `.create` stage (whether defaults, overrides or a combination of the two). 

The function is also `public` because we now allow you to set `{ autoConnect: false }` when creating a Tether Agent in case you have reason to create the TetherAgent instance first without automatically connecting as well.

## MessagePack included
The library `@msgpack/msgpack` is now included in the JS Base Agent itself as a dependency, and the `encode` and `decode` functions are exported from the library.

MessagePack works great, so why not?

This means that future client applications only need to include "tether-agent" as a dependency, and they get the MessagePack encoding and decoding as well without needing to remember a separate library.

This also means that, in future, we could easily provide (optional?) automatic encode-and-publish and/or automatic receive-and-decode functionality in the Base Agent if we like. We already do something like this in the Rust Base Agent, for example.

## Connection/state changes
The function `getIsConnected` was surprisingly unreliable at reporting whether the Tether Agent (MQTT client) was actually connected or not.

The `client` from the MQTT library will apparently return `true` for `.isConnected` even when the connection has failed.

The v3 Tether Agent therefore keeps track of the State (INITIALISING, CONNECTING, CONNECTED, ERRORED) a lot more carefully, and tries to report `getIsConnected()` more reliably.

## Minor Changes
- `Input` -> `InputPlug` and `Output` -> `OutputPlug`
- There is no special `onMessage`or `.onMessageOnce` function for Input(Plug)s - a standard Event Emitter pattern is used instead, i.e. `.on("message", (payload, topic) => {})` and `.once("message", (payload, topic) => {})`
- Subscribing without an active connection is not (currently) allowed any more. Can't think of any reason to allow it, and makes even less sense when the Plugs are "owned" by the end-user application rather than the TetherAgent instance; how would we ensure that actual subscription is done "later"?
- Utility functions such as "parsePlugName" relating to Plugs have been moved to `Plugs.ts`
- UUID library has been removed completely, because it generates very lengthy "ID" strings that are hard to read and not very useful. In the meantime the concept of an Agent "ID" has been extended to a "grouping" so it makes even less sense to generate such unique identities by default. If the end-user needs to group (or distinguish/split) agents with such granularity then they should rather do this explicitly, themselves. For example, it might make more sense to use a MAC ID or some other identifier. Now, we default to `"any"` instead.
- Added `getState()` function which can give more detail than `getIsConnected()` on its own

### CODE REVIEW

**Comment by ralphkok** [comment]
I agree with almost everything here, but I have some questions/thoughts:

1. Why have different ways of instantiating input vs output plugs? It seems to me that this is unnecessarily confusing, and I would opt to implement `OutputPlug.create(...)` as well.
2. I would suggest that the other languages' base agents match implementation details to this, so as to not end up with ever diverging approaches between them.
3. Iirc, we allowed subscribing without a connection to let the agent automatically subscribe once the connection could be established, and resubscribe should the connect be lost and regained. This was to remove the need to handle reconnection response, but thinking about it more, it's just as easy (and cleaner) to do this in the connection handler.

Other than that, I think these are all great changes!

**Comment by anselanza** [comment]
> Why have different ways of instantiating input vs output plugs? It seems to me that this is unnecessarily confusing, and I would opt to implement OutputPlug.create(...) as well.

Yes, this one doesn't feel 100% right yet.

The main reason is that Output Plugs can be created immediately (not async or anything) whereas creating Input Plugs always implies the subscription action, which is indeed asynchronous. 

We used to resolve this by sort of hiding the difference (automatically subscribing when needed, for example) but it made more sense for me to make the fundamental difference more explicit.

We *could* allow `new InputPlug` to asynchronously run the `subscribe` action "behind the scenes" but then there is no way for the end-user to know when it has completed (or if it was successful, for that matter).

**Comment by ralphkok** [comment]
@anselanza 
> We _could_ allow `new InputPlug` to asynchronously run the `subscribe` action "behind the scenes" but then there is no way for the end-user to know when it has completed (or if it was successful, for that matter).
No I agree that `new InputPlug` is undesirable, but why not have a synchronous `OutputPlug.create` instead? Or even in addition? What mostly bothers me is the need to understand the underlying mechanism in order to remember which method to use to instantiate a plug.

**Comment by anselanza** [comment]
@ralphkok 
> why not have a synchronous `OutputPlug.create` instead

This would certainly work. You would need to remember that it has a very different return type compared to `InputPlug.create`, though. 

- `OutputPlug.create` -> returns an instance of OutputPlug, so you can do `const plug = OutputPlug.create(agent)`
- `InputPlug.create`-> returns a Promise which resolves with an instance of InputPlug, so you **should** do `const plug = await InputPlug.create`, or even better `try { const plug = await InputPlug.create(agent) } catch (e) { ... }`. If you did `const plug = InputPlug.create(agent)` instead, you wouldn't see an error until you tried to call a method on what you thought was an instance of InputPlug but was actually a promise.

**Pull request merged**
