### PR TITLE
Tether Utils as a library

### PR DESCRIPTION
**Pull request by anselanza**
This retains all the previous functionality of the `tether` command, but also allows the utility functions such as record, playback, etc. to be used programmatically, i.e. via an API rather than only a command-line interface.

The crate thus becomes a library in addition to retaining the `tether` binary as before - but even the binary uses the same library modules and functions.

The `examples/api.rs` demonstrates how the API would be used; this has also been implemented and tested in the latest version of Tether egui.

### CODE REVIEW

**Comment by ralphkok** [comment]
This all looks very good to me. Just a few small questions/remarks.

I noticed that `ReceiveOptions` and `TopicOptions` both have a `subscribe_topic` field and nothing else. I feel that it could instead be named simply `topic`, as the context implies it being about subscription not publication. What do you think?

Regarding `SendOptions`, I'm a bit confused about the `custom_message` field. When using the `send` utility, surely we would expect you to provide the data to send? Why is this specified as a "custom" message, with a default set of dummy data being sent when you don't provide any message data? It feels a bit strange that when sending, there is any default data at all, no?

And finally I'm wondering about `Insights`, if it would be useful to add a mapping of ids, roles, plugs and topics, beyond separate lists of them? Perhaps that's something to be implemented in a separate agent though, if we want it. Might be beyond the realm of what this utility should provide. Interested to hear what you think about that.

**Comment by anselanza** [comment]
I think these are all good suggestions, and well spotted!

Agreed that the default message thing is a bit weird. It was based on how the original (NodeJS) version worked. But maybe it could work like this instead:
- The default message could be literally an empty message
- Otherwise, specify your own message
- Finally, we could provide an optional flag where a pre-generated "dummy message" is created for you (sometimes it's a pain to write the weird escaped slashes/quotes/brackets if you just want to check that messaging is working at all)

`Insights` could definitely be improved. I do like the idea of representing a kind of "tree view" or something. For now, the data is mostly there, but the CLI (`tether topics`) could organise and format the output nicely to give something a bit more useful.

**Comment by ralphkok** [comment]
Agreed on all these points. Re the default message, I think it being empty makes a lot of sense, and yes I do see the use of the dummy message and auto-generating that for testing purposes.

For insights, I agree that a tree view would be quite useful, and about as complex as it needs to be for this utility.
I could see a more advanced UI in our future where you can see connections being formed on a 2D map of some sort, based on the subscriptions and who is receiving what, but that is way beyond the scope of this library.

**Comment by anselanza** [comment]
I have added to the `Insights` struct so that you build a basic "tree" structure, and display it, from the same saved topics.

Here is an example of the output:
```
 x5 Topics: ["utils/customid/testMessages", "testAgent/any/testMessages", "trackingSim/de1302c0-8bbb-4051-9961-efa7cade3016/trackedPoints", "utils/any/evenMore", "utils/any/anotherPlug"] 
    x3 Roles: ["utils", "testAgent", "trackingSim"] 
    x3 IDs: ["customid", "any", "de1302c0-8bbb-4051-9961-efa7cade3016"] 
    x4 Plugs: ["testMessages", "trackedPoints", "evenMore", "anotherPlug"] 
    x55 Messages total 
    
    utils
     
        - customid
        - any
     
            - testMessages
            - evenMore
            - anotherPlug
    
    testAgent
     
        - any
     
            - testMessages
    
    trackingSim
     
        - de1302c0-8bbb-4051-9961-efa7cade3016
     
            - trackedPoints
```
The example is showing three Agents (Roles), with 2 IDs for `utils` and 1 for each of `testAgent` and `trackingSim`. There are 3 (output) plugs for `utils` and the others have 1 each.

**Pull request merged**
